; Error return codes for handles.
ERROR_HANDLE_FILE_OPEN:		equ	-1
ERROR_HANDLE_HEADER_NOT_FOUND:	equ	-2
ERROR_HANDLE_ALLOCATE_FAIL:	equ	-3
ERROR_HANDLE_FILE_READ:		equ	-4
ERROR_HANDLE_GENERIC:		equ	-5